import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HEADER_HEIGHT = 64

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`app ${geistMono.variable} ${geistMono.className} antialiased`}
      >
        <div
            className="dashboard flex flex-auto flex-col bg-background"
        >
            <div className="flex flex-auto min-w-0">
                {/* <div className="sidebar min-w-72.5"></div> */}
                <div className="flex flex-col flex-auto min-h-screen min-w-0 relative w-full">
                    <header className="header sticky top-0 z-20 flex w-full shadow-sm dark:shadow-2xl bg-zinc-950">
                        <div className="flex items-center px-6" style={{ height: HEADER_HEIGHT }}>
                            <Link href="/dashboard" className="hover:text-gray-300 mr-4">
                            Dashboard
                            </Link>
                            <Link href="/dashboard/analytics" className="hover:text-gray-300 mr-4">
                            Analytics
                            </Link>
                        </div>
                    </header>
                    <div className="h-full flex flex-auto flex-col">
                        {children}
                    </div>
                </div>
            </div>
        </div>
      </body>
    </html>
  );
}
